---
title: "Query ECT"
author: "yosiro.com"
date: "20/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r}
# Load Packages
library(tidyverse)
library(rio)
library(RODBC)
library(knitr)
library(DBI)
library(RColorBrewer)
library(plyr)
library(lubridate)

# Set Working Directory
setwd("C:/Users/ASUS/Desktop")


# Connect to Database
dta <- odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=D:/Cloud Data/OneDrive - Universitas Terbuka/UPT Bahasa/2 Yosi Folder/Database Projects/UPT BAHASA Database Master.accdb")

# Load Tables
tbl_mhs_data <- sqlFetch(dta, "mhs_data_T") %>% as_tibble()
tbl_mhs_kelas <- sqlFetch(dta, "mhs_kelas_T") %>% as_tibble()
tbl_dosen <- sqlFetch(dta, "dosen") %>% as_tibble()
tbl_jurusan <- sqlFetch(dta, "jurusan") %>% as_tibble()
tbl_pengawas <- sqlFetch(dta, "pengawas") %>% as_tibble()
tbl_prodi <- sqlFetch(dta, "prodi") %>% as_tibble()
tbl_mhs_daftar_toeic <- sqlFetch(dta, "mhs_daftar_toeic_T") %>% as_tibble()
tbl_mhs_score_toeic <- sqlFetch(dta, "mhs_score_toeic_T") %>% as_tibble()
tbl_mhs_daftar_toeic <- sqlFetch(dta, "mhs_daftar_toeic_T") %>% as_tibble()
tbl_mhs_score_toeic <- sqlFetch(dta, "mhs_score_toeic_T") %>% as_tibble()

tbl_rumus_toeic_listening <- sqlFetch(dta, "rumus_toeic_listening") %>% as_tibble()
tbl_rumus_toeic_reading <- sqlFetch(dta, "rumus_toeic_reading") %>% as_tibble()

tbl_rumus_toeic_listening <- sqlFetch(dta, "rumus_toeic_listening") %>% as_tibble()
tbl_rumus_toeic_reading$ID <- as.numeric(tbl_rumus_toeic_reading$ID)
tbl_rumus_toeic_listening$ID <- as.numeric(tbl_rumus_toeic_listening$ID)

tabel <- tbl_mhs_score_toeic %>% 
        select(ISO = mhs_daftar_toeic_ID, ID_mhs = mhs_data_ID, ID_ect = ID, l1:g2, skor = total, hadir)
tabel <- merge(tabel, tbl_mhs_data, by.x = "ID_mhs", by.y = "ID", all.x = T )
tabel <- tabel %>% 
        select(ISO, ID_mhs, ID_ect, l1:g2, skor, hadir, nim, mhs_kelas_ID, jenis_kelamin = sex, nama, tempat_lahir, tanggal_lahir) 
tabel <- merge(tabel, tbl_mhs_kelas, by.x = "mhs_kelas_ID", by.y = "ID", all.x = T) 
tabel <- tabel %>% 
        select(ISO, ID_mhs, ID_ect, l1:g2, skor, hadir, nama, nim, jenis_kelamin, prodi_ID, semester, kelas, tempat_lahir, tanggal_lahir)
tabel <- merge(tabel, tbl_prodi, by.x = "prodi_ID", by.y = "ID") 
tabel <- tabel %>% select(ISO, nim, nama, jenis_kelamin, l1:g2, skor, hadir,  Prodi = singkatan, semester, kelas, program_studi = prodi, tempat_lahir, tanggal_lahir) 
tabel <- merge(tabel, tbl_mhs_daftar_toeic, by.x = "ISO", by.y = "ID")
tabel <- tabel %>% select(ISO, nim, nama, jenis_kelamin, l1:g2, skor, hadir,  Prodi, semester, kelas, program_studi, tempat_lahir, tanggal_lahir, tanggal, keterangan_1, ruangan)

```

# Laporan ECT per Prodi

```{r}
# Daftar prodi yang telah ikut
tabel %>% select(keterangan_1) %>% count()

tabel_kegiatan <- tabel %>% filter(keterangan_1 == "ECT Mahasiswa Semester Akhir 2021")

prodi <- tabel_kegiatan %>% select(Prodi)
prodi <- unique(prodi)
prodi <- prodi$Prodi

x <- tabel_kegiatan %>% select(Prodi, nama, nim, tempat_lahir, tanggal_lahir, l1, g1, l2, g2, skor) 
x$tanggal_lahir <- as.POSIXct(x$tanggal_lahir, tz = "Asia/Bangkok")
x$tanggal_lahir <- format(x$tanggal_lahir, format = "%d/%m/%Y")
x <- x %>% filter(!is.na(skor), skor > 0) %>% mutate(ttl = paste(tempat_lahir, ",", " ", tanggal_lahir, sep = ""))
x <- x %>% select(Prodi, nama, nim, ttl, l1:g2, skor)

# Simpan tabel tiap prodi ke excel
for(i in prodi){
        g <- x %>% filter(Prodi == i)
        export(g, file = paste0(i, ".xlsx", sep=""))
}

```

